title: Paridhi Gupta
email: paridhi.chandra@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  PhD Student in Electrical and Computer Engineering at UW-Madison.
baseurl: "" 
url: "" 
theme: minima
plugins:
  - jekyll-seo-tag